require.config({
	baseUrl: "js",
	paths: {
		jquery: "vendors/jquery-2.1.4",
		underscore: "vendors/underscore",
		docPager: "myscript/docsPage",
		fuzzyPinyin: "myscript/fuzzyPinyin",
		accordion: "vendors/accordion/accordion",
		bootstrap: "vendors/bootstrap/bootstrap",
		myVue: "myscript/myVue",
		vue: "vendors/vue",
		myVueComponent:'myscript/myVueComponent'
	},
	shim: {
		underscore: {
			exports: "_"
		},
		accordion: {
			deps: ["jquery"],
			exports: "Accordion"
		},
		bootstrap: {
			deps: ["jquery"],
		}
	},
	waitSeconds: 15
});
jsonData = [{
	"id": 1,
	"parentId": "0",
	"text": "蓄滞洪区文档测试",
	"nodes": [{
		"id": 2,
		"parentId": "1",
		"text": "1",
		"nodes": [],
		"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\1",
		"isFlder": true
	}, {
		"id": 3,
		"parentId": "1",
		"text": "2",
		"nodes": [],
		"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\2",
		"isFlder": true
	}, {
		"id": 4,
		"parentId": "1",
		"text": "业务类",
		"nodes": [{
			"id": 5,
			"parentId": "4",
			"text": "松花江流域",
			"nodes": [],
			"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\松花江流域",
			"isFlder": true
		}, {
			"id": 6,
			"parentId": "4",
			"text": "淮河流域",
			"nodes": [{
				"id": 7,
				"parentId": "6",
				"fileType": "text",
				"text": "上传演示文件.docx",
				"isFlder": false
			}],
			"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\淮河流域",
			"isFlder": true
		}, {
			"id": 8,
			"parentId": "4",
			"text": "长江流域_F",
			"nodes": [{
				"id": 9,
				"parentId": "8",
				"fileType": "pdf",
				"text": "DisplayObjectModel.pdf",
				"isFlder": false
			}, {
				"id": 10,
				"parentId": "8",
				"fileType": "text",
				"text": "GIS.txt",
				"isFlder": false
			}, {
				"id": 11,
				"parentId": "8",
				"fileType": "text",
				"text": "JaveWeb.doc",
				"isFlder": false
			}, {
				"id": 12,
				"parentId": "8",
				"fileType": "text",
				"text": "JaveWeb.docx",
				"isFlder": false
			}, {
				"id": 13,
				"parentId": "8",
				"fileType": "img",
				"text": "topo.jpg",
				"isFlder": false
			}, {
				"id": 14,
				"parentId": "8",
				"fileType": "text",
				"text": "三维GIS开发测试题.txt",
				"isFlder": false
			}, {
				"id": 15,
				"parentId": "8",
				"text": "江南陆城_FFF0000241",
				"nodes": [{
					"id": 16,
					"parentId": "15",
					"fileType": "text",
					"text": "三维GIS开发测试题.txt",
					"isFlder": false
				}, {
					"id": 17,
					"parentId": "15",
					"text": "复核",
					"nodes": [{
						"id": 18,
						"parentId": "17",
						"fileType": "text",
						"text": "GIS.txt",
						"isFlder": false
					}, {
						"id": 19,
						"parentId": "17",
						"fileType": "text",
						"text": "JaveWeb.doc",
						"isFlder": false
					}, {
						"id": 20,
						"parentId": "17",
						"fileType": "text",
						"text": "JaveWeb.docx",
						"isFlder": false
					}, {
						"id": 21,
						"parentId": "17",
						"fileType": "img",
						"text": "topo.jpg",
						"isFlder": false
					}, {
						"id": 22,
						"parentId": "17",
						"fileType": "text",
						"text": "三维GIS开发测试题.txt",
						"isFlder": false
					}, {
						"id": 23,
						"parentId": "17",
						"fileType": "text",
						"text": "上传演示文件.docx",
						"isFlder": false
					}, {
						"id": 24,
						"parentId": "17",
						"text": "堤防_df",
						"nodes": [],
						"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\堤防_df",
						"isFlder": true
					}, {
						"id": 25,
						"parentId": "17",
						"text": "安全区_aqq",
						"nodes": [],
						"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\安全区_aqq",
						"isFlder": true
					}, {
						"id": 26,
						"parentId": "17",
						"text": "安全台_aqt",
						"nodes": [{
							"id": 27,
							"parentId": "26",
							"text": "鸭栏",
							"nodes": [{
								"id": 28,
								"parentId": "27",
								"fileType": "dwg",
								"text": "H49 G 057086鸭栏安全台.dwg",
								"isFlder": false
							}],
							"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\安全台_aqt\\鸭栏",
							"isFlder": true
						}],
						"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\安全台_aqt",
						"isFlder": true
					}, {
						"id": 29,
						"parentId": "17",
						"text": "泵站_bz",
						"nodes": [{
							"id": 30,
							"parentId": "29",
							"text": "儒溪水厂泵站",
							"nodes": [{
								"id": 31,
								"parentId": "30",
								"fileType": "dwg",
								"text": "H49 G 057086儒溪水厂泵站图.dwg",
								"isFlder": false
							}, {
								"id": 32,
								"parentId": "30",
								"fileType": "img",
								"text": "儒溪水厂泵站.JPG",
								"isFlder": false
							}],
							"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\泵站_bz\\儒溪水厂泵站",
							"isFlder": true
						}, {
							"id": 33,
							"parentId": "29",
							"text": "天螺山电排站",
							"nodes": [{
								"id": 34,
								"parentId": "33",
								"fileType": "dwg",
								"text": "H49 G 058085_天螺山电排站图.dwg",
								"isFlder": false
							}, {
								"id": 35,
								"parentId": "33",
								"fileType": "img",
								"text": "IMG__8天镙山电排8.JPG",
								"isFlder": false
							}, {
								"id": 36,
								"parentId": "33",
								"fileType": "img",
								"text": "IMG___天镙山电排7.JPG",
								"isFlder": false
							}, {
								"id": 37,
								"parentId": "33",
								"fileType": "img",
								"text": "IMG___天镙山电排9.JPG",
								"isFlder": false
							}, {
								"id": 38,
								"parentId": "33",
								"fileType": "img",
								"text": "IMG__天镙山电排11.JPG",
								"isFlder": false
							}, {
								"id": 39,
								"parentId": "33",
								"fileType": "img",
								"text": "IMG_天镙山电排10.JPG",
								"isFlder": false
							}, {
								"id": 40,
								"parentId": "33",
								"fileType": "img",
								"text": "IMG_天镙山电排2.JPG",
								"isFlder": false
							}, {
								"id": 41,
								"parentId": "33",
								"fileType": "img",
								"text": "IMG_天镙山电排5.PNG",
								"isFlder": false
							}, {
								"id": 42,
								"parentId": "33",
								"fileType": "img",
								"text": "IMG_鸭栏电排站1.JPG",
								"isFlder": false
							}, {
								"id": 43,
								"parentId": "33",
								"fileType": "img",
								"text": "IMG_鸭栏电排站2.JPG",
								"isFlder": false
							}, {
								"id": 44,
								"parentId": "33",
								"fileType": "img",
								"text": "IMG_鸭栏电排站5.JPG",
								"isFlder": false
							}, {
								"id": 45,
								"parentId": "33",
								"fileType": "img",
								"text": "IMG_鸭栏电排站8.JPG",
								"isFlder": false
							}, {
								"id": 46,
								"parentId": "33",
								"fileType": "img",
								"text": "_IMG_天镙山电排3.JPG",
								"isFlder": false
							}, {
								"id": 47,
								"parentId": "33",
								"fileType": "img",
								"text": "_IMG_天镙山电排4.JPG",
								"isFlder": false
							}, {
								"id": 48,
								"parentId": "33",
								"fileType": "img",
								"text": "_IMG_天镙山电排6.JPG",
								"isFlder": false
							}],
							"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\泵站_bz\\天螺山电排站",
							"isFlder": true
						}, {
							"id": 49,
							"parentId": "29",
							"text": "鸭栏电排站",
							"nodes": [{
								"id": 50,
								"parentId": "49",
								"text": "3dmodel",
								"nodes": [{
									"id": 51,
									"parentId": "50",
									"fileType": "video",
									"text": "新设电排.mp4",
									"isFlder": false
								}, {
									"id": 52,
									"parentId": "50",
									"fileType": "img",
									"text": "电排1.JPG",
									"isFlder": false
								}, {
									"id": 53,
									"parentId": "50",
									"fileType": "img",
									"text": "电排2.JPG",
									"isFlder": false
								}, {
									"id": 54,
									"parentId": "50",
									"fileType": "img",
									"text": "鸭栏1.jpg",
									"isFlder": false
								}, {
									"id": 55,
									"parentId": "50",
									"fileType": "img",
									"text": "鸭栏2.jpg",
									"isFlder": false
								}, {
									"id": 56,
									"parentId": "50",
									"fileType": "video",
									"text": "鸭栏电排.mp4",
									"isFlder": false
								}],
								"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\泵站_bz\\鸭栏电排站\\3dmodel",
								"isFlder": true
							}, {
								"id": 57,
								"parentId": "49",
								"fileType": "dwg",
								"text": "H49 G 鸭栏泄洪、鸭栏电排站地形图闸.dwg",
								"isFlder": false
							}, {
								"id": 58,
								"parentId": "49",
								"fileType": "img",
								"text": "IMG__鸭栏电排站3.JPG",
								"isFlder": false
							}, {
								"id": 59,
								"parentId": "49",
								"fileType": "img",
								"text": "IMG__鸭栏电排站4.JPG",
								"isFlder": false
							}, {
								"id": 60,
								"parentId": "49",
								"fileType": "img",
								"text": "IMG__鸭栏电排站6.JPG",
								"isFlder": false
							}, {
								"id": 61,
								"parentId": "49",
								"fileType": "video",
								"text": "鸭栏.mp4",
								"isFlder": false
							}],
							"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\泵站_bz\\鸭栏电排站",
							"isFlder": true
						}],
						"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\泵站_bz",
						"isFlder": true
					}, {
						"id": 62,
						"parentId": "17",
						"fileType": "pdf",
						"text": "测试.pdf",
						"isFlder": false
					}, {
						"id": 63,
						"parentId": "17",
						"fileType": "text",
						"text": "点要素（模板文件）.txt",
						"isFlder": false
					}, {
						"id": 64,
						"parentId": "17",
						"text": "转移桥梁_ql",
						"nodes": [{
							"id": 65,
							"parentId": "64",
							"text": "华新桥",
							"nodes": [{
								"id": 66,
								"parentId": "65",
								"fileType": "dwg",
								"text": "H49 G 058086华新桥、钢铁桥.dwg",
								"isFlder": false
							}, {
								"id": 67,
								"parentId": "65",
								"fileType": "img",
								"text": "华新桥.JPG",
								"isFlder": false
							}],
							"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\转移桥梁_ql\\华新桥",
							"isFlder": true
						}, {
							"id": 68,
							"parentId": "64",
							"text": "南太桥",
							"nodes": [{
								"id": 69,
								"parentId": "68",
								"fileType": "dwg",
								"text": "H49 G 060086草湖桥、粮湖桥、太平桥、南太桥.dwg",
								"isFlder": false
							}, {
								"id": 70,
								"parentId": "68",
								"fileType": "img",
								"text": "南太桥.JPG",
								"isFlder": false
							}],
							"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\转移桥梁_ql\\南太桥",
							"isFlder": true
						}, {
							"id": 71,
							"parentId": "64",
							"text": "友谊桥",
							"nodes": [{
								"id": 72,
								"parentId": "71",
								"fileType": "dwg",
								"text": "H49 G 060085幸福桥、友谊桥、团结桥及207国道上一座桥、.dwg",
								"isFlder": false
							}, {
								"id": 73,
								"parentId": "71",
								"fileType": "img",
								"text": "友谊桥.JPG",
								"isFlder": false
							}],
							"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\转移桥梁_ql\\友谊桥",
							"isFlder": true
						}, {
							"id": 74,
							"parentId": "64",
							"text": "吓形嘴桥",
							"nodes": [{
								"id": 75,
								"parentId": "74",
								"fileType": "dwg",
								"text": "H49 G 057086吓形嘴桥、王家咀桥.dwg",
								"isFlder": false
							}, {
								"id": 76,
								"parentId": "74",
								"fileType": "img",
								"text": "吓形嘴桥.JPG",
								"isFlder": false
							}],
							"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\转移桥梁_ql\\吓形嘴桥",
							"isFlder": true
						}, {
							"id": 77,
							"parentId": "64",
							"text": "团结桥",
							"nodes": [{
								"id": 78,
								"parentId": "77",
								"fileType": "dwg",
								"text": "H49 G 060085幸福桥、友谊桥、团结桥及207国道上一座桥、.dwg",
								"isFlder": false
							}, {
								"id": 79,
								"parentId": "77",
								"fileType": "img",
								"text": "团结桥.JPG",
								"isFlder": false
							}],
							"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\转移桥梁_ql\\团结桥",
							"isFlder": true
						}, {
							"id": 80,
							"parentId": "64",
							"text": "太平桥",
							"nodes": [{
								"id": 81,
								"parentId": "80",
								"fileType": "dwg",
								"text": "H49 G 060086草湖桥、粮湖桥、太平桥、南太桥.dwg",
								"isFlder": false
							}, {
								"id": 82,
								"parentId": "80",
								"fileType": "img",
								"text": "太平桥.JPG",
								"isFlder": false
							}],
							"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\转移桥梁_ql\\太平桥",
							"isFlder": true
						}, {
							"id": 83,
							"parentId": "64",
							"text": "幸福桥",
							"nodes": [{
								"id": 84,
								"parentId": "83",
								"fileType": "dwg",
								"text": "H49 G 060085幸福桥、友谊桥、团结桥及207国道上一座桥、.dwg",
								"isFlder": false
							}, {
								"id": 85,
								"parentId": "83",
								"fileType": "img",
								"text": "幸福桥.JPG",
								"isFlder": false
							}],
							"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\转移桥梁_ql\\幸福桥",
							"isFlder": true
						}, {
							"id": 86,
							"parentId": "64",
							"text": "王家咀桥",
							"nodes": [{
								"id": 87,
								"parentId": "86",
								"fileType": "dwg",
								"text": "H49 G 057086吓形嘴桥、王家咀桥.dwg",
								"isFlder": false
							}, {
								"id": 88,
								"parentId": "86",
								"fileType": "img",
								"text": "王家咀桥.JPG",
								"isFlder": false
							}],
							"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\转移桥梁_ql\\王家咀桥",
							"isFlder": true
						}, {
							"id": 89,
							"parentId": "64",
							"text": "省塘桥",
							"nodes": [{
								"id": 90,
								"parentId": "89",
								"fileType": "dwg",
								"text": "H49 G 059086立帅桥、省塘桥.dwg",
								"isFlder": false
							}, {
								"id": 91,
								"parentId": "89",
								"fileType": "img",
								"text": "省塘桥.JPG",
								"isFlder": false
							}],
							"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\转移桥梁_ql\\省塘桥",
							"isFlder": true
						}, {
							"id": 92,
							"parentId": "64",
							"text": "立帅桥",
							"nodes": [{
								"id": 93,
								"parentId": "92",
								"fileType": "dwg",
								"text": "H49 G 059086立帅桥、省塘桥.dwg",
								"isFlder": false
							}, {
								"id": 94,
								"parentId": "92",
								"fileType": "img",
								"text": "立帅桥1.JPG",
								"isFlder": false
							}, {
								"id": 95,
								"parentId": "92",
								"fileType": "img",
								"text": "立帅桥2旧桥.JPG",
								"isFlder": false
							}],
							"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\转移桥梁_ql\\立帅桥",
							"isFlder": true
						}, {
							"id": 96,
							"parentId": "64",
							"text": "粮湖桥",
							"nodes": [{
								"id": 97,
								"parentId": "96",
								"fileType": "dwg",
								"text": "H49 G 060086草湖桥、粮湖桥、太平桥、南太桥.dwg",
								"isFlder": false
							}, {
								"id": 98,
								"parentId": "96",
								"fileType": "img",
								"text": "粮湖桥.JPG",
								"isFlder": false
							}],
							"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\转移桥梁_ql\\粮湖桥",
							"isFlder": true
						}, {
							"id": 99,
							"parentId": "64",
							"text": "草湖桥",
							"nodes": [{
								"id": 100,
								"parentId": "99",
								"fileType": "dwg",
								"text": "H49 G 060086草湖桥、粮湖桥、太平桥、南太桥.dwg",
								"isFlder": false
							}, {
								"id": 101,
								"parentId": "99",
								"fileType": "img",
								"text": "草湖桥.JPG",
								"isFlder": false
							}],
							"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\转移桥梁_ql\\草湖桥",
							"isFlder": true
						}, {
							"id": 102,
							"parentId": "64",
							"text": "钢铁桥",
							"nodes": [{
								"id": 103,
								"parentId": "102",
								"fileType": "dwg",
								"text": "H49 G 058086华新桥、钢铁桥.dwg",
								"isFlder": false
							}, {
								"id": 104,
								"parentId": "102",
								"fileType": "img",
								"text": "钢铁桥.JPG",
								"isFlder": false
							}],
							"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\转移桥梁_ql\\钢铁桥",
							"isFlder": true
						}],
						"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\转移桥梁_ql",
						"isFlder": true
					}, {
						"id": 105,
						"parentId": "17",
						"text": "闸_za",
						"nodes": [{
							"id": 106,
							"parentId": "105",
							"text": "曾家叉泄洪闸",
							"nodes": [{
								"id": 107,
								"parentId": "106",
								"text": "3dmodel",
								"nodes": [{
									"id": 108,
									"parentId": "107",
									"fileType": "video",
									"text": "新设电排.mp4",
									"isFlder": false
								}, {
									"id": 109,
									"parentId": "107",
									"fileType": "img",
									"text": "电排1.JPG",
									"isFlder": false
								}, {
									"id": 110,
									"parentId": "107",
									"fileType": "img",
									"text": "电排2.JPG",
									"isFlder": false
								}, {
									"id": 111,
									"parentId": "107",
									"fileType": "img",
									"text": "鸭栏1.jpg",
									"isFlder": false
								}, {
									"id": 112,
									"parentId": "107",
									"fileType": "img",
									"text": "鸭栏2.jpg",
									"isFlder": false
								}, {
									"id": 113,
									"parentId": "107",
									"fileType": "video",
									"text": "鸭栏电排.mp4",
									"isFlder": false
								}],
								"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\闸_za\\曾家叉泄洪闸\\3dmodel",
								"isFlder": true
							}, {
								"id": 114,
								"parentId": "106",
								"fileType": "img",
								"text": "曾家叉泄洪闸1.JPG",
								"isFlder": false
							}, {
								"id": 115,
								"parentId": "106",
								"fileType": "img",
								"text": "曾家叉泄洪闸2.JPG",
								"isFlder": false
							}, {
								"id": 116,
								"parentId": "106",
								"fileType": "video",
								"text": "鸭栏.mp4",
								"isFlder": false
							}],
							"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\闸_za\\曾家叉泄洪闸",
							"isFlder": true
						}, {
							"id": 117,
							"parentId": "105",
							"text": "鸭栏泄洪闸",
							"nodes": [{
								"id": 118,
								"parentId": "117",
								"text": "3dmodel",
								"nodes": [{
									"id": 119,
									"parentId": "118",
									"fileType": "video",
									"text": "新设电排.mp4",
									"isFlder": false
								}, {
									"id": 120,
									"parentId": "118",
									"fileType": "img",
									"text": "电排1.JPG",
									"isFlder": false
								}, {
									"id": 121,
									"parentId": "118",
									"fileType": "img",
									"text": "电排2.JPG",
									"isFlder": false
								}, {
									"id": 122,
									"parentId": "118",
									"fileType": "img",
									"text": "鸭栏1.jpg",
									"isFlder": false
								}, {
									"id": 123,
									"parentId": "118",
									"fileType": "img",
									"text": "鸭栏2.jpg",
									"isFlder": false
								}, {
									"id": 124,
									"parentId": "118",
									"fileType": "video",
									"text": "鸭栏电排.mp4",
									"isFlder": false
								}],
								"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\闸_za\\鸭栏泄洪闸\\3dmodel",
								"isFlder": true
							}, {
								"id": 125,
								"parentId": "117",
								"fileType": "pdf",
								"text": "DisplayObjectModel.pdf",
								"isFlder": false
							}, {
								"id": 126,
								"parentId": "117",
								"fileType": "text",
								"text": "GIS.txt",
								"isFlder": false
							}, {
								"id": 127,
								"parentId": "117",
								"fileType": "dwg",
								"text": "H49 G 鸭栏泄洪、鸭栏电排站地形图闸.dwg",
								"isFlder": false
							}, {
								"id": 128,
								"parentId": "117",
								"fileType": "img",
								"text": "IMG__鸭栏泄洪闸2.JPG",
								"isFlder": false
							}, {
								"id": 129,
								"parentId": "117",
								"fileType": "img",
								"text": "IMG__鸭栏泄洪闸3.JPG",
								"isFlder": false
							}, {
								"id": 130,
								"parentId": "117",
								"fileType": "img",
								"text": "IMG__鸭栏泄洪闸4.JPG",
								"isFlder": false
							}, {
								"id": 131,
								"parentId": "117",
								"fileType": "img",
								"text": "IMG__鸭栏泄洪闸5.JPG",
								"isFlder": false
							}, {
								"id": 132,
								"parentId": "117",
								"fileType": "img",
								"text": "IMG_鸭栏泄洪闸1.JPG",
								"isFlder": false
							}, {
								"id": 133,
								"parentId": "117",
								"fileType": "video",
								"text": "鸭栏.mp4",
								"isFlder": false
							}],
							"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\闸_za\\鸭栏泄洪闸",
							"isFlder": true
						}],
						"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\闸_za",
						"isFlder": true
					}, {
						"id": 134,
						"parentId": "17",
						"text": "陆城水工建筑照片",
						"nodes": [],
						"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核\\陆城水工建筑照片",
						"isFlder": true
					}],
					"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241\\复核",
					"isFlder": true
				}],
				"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F\\江南陆城_FFF0000241",
				"isFlder": true
			}, {
				"id": 135,
				"parentId": "8",
				"fileType": "pdf",
				"text": "测试.pdf",
				"isFlder": false
			}],
			"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类\\长江流域_F",
			"isFlder": true
		}, {
			"id": 136,
			"parentId": "4",
			"fileType": "img",
			"text": "长江流域_Ftopo.jpg",
			"isFlder": false
		}],
		"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试\\业务类",
		"isFlder": true
	}],
	"href": "E:\\2015\\2015蓄滞洪区\\数据\\江南陆城下\\蓄滞洪区文档测试",
	"isFlder": true
}];

require(["jquery", "docPager", "myVueComponent"], function($, docPager, myVue) {

	$("#backBtn").click(function() {
		var backNodeId = $("#breadcrumb").children()
			.children("a:last").attr("nodeId");
		if (backNodeId)
			docPager.updateData(backNodeId);
	});
	$("#searchArea").bind("keyup", function(e) {
		if (e.keyCode === 13) {
			window.docPager.search(document.getElementById("searchArea").value);
		}
	});
	$("#goBtn").bind("click", function() {
		window.docPager.search(document.getElementById("searchArea").value);
	});


	//	docPager.init(jsonData);
	//	docPager.updateAccord();

	myVue.init(jsonData[0].nodes);

})